# Generated by Django 3.2.6 on 2021-08-23 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('login', models.CharField(help_text='Informe um login', max_length=200, unique=True)),
                ('funcao', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('unidade_saude', models.CharField(blank=True, max_length=255, null=True)),
                ('perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email address')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='media')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Define se o usuario pode fazer login neste site de administração.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designa se esse usuário deve ser tratado como ativo. Desmarque isso ao invés de excluir conta.', verbose_name='active')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data adesão')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
